name: CI
on:
  push:
    branches:
    - shebang-doc-test
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  docs-tests:
    # for now, let's run those tests only on ubuntu
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: VirtusLab/scala-cli-setup@7e6a0b2468fc28b94936417e4cad385e380ac735
      with:
        jvm: "zulu:17"
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: scala-cli version
    - name: Test documentation
      run: ./mill -i docs-tests.test 'sclicheck.DocTests.guide shebang'
