name: CI
on:
  push:
    branches:
    - main
    - test-m1
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  native-macos-m1-tests:
    timeout-minutes: 120
    runs-on: "macOS-m1"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - run: ls /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/bin
      - uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          apps: ""
          jvm: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz"
      - name: Native integration tests
        run: ./mill integration.test.jvm 'scala.cli.integration.RunTestsDefault.scalapy native'
        env:
          UPDATE_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCALA_CLI_IT_FORCED_LAUNCHER_DIRECTORY: artifacts/
          SCALA_CLI_SODIUM_JNI_ALLOW: false
